"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.partner_offer_session import PartnerOfferSession

globals()['PartnerOfferSession'] = PartnerOfferSession
from pxcloud_api_client.model.partner_offer_with_sessions import PartnerOfferWithSessions


class TestPartnerOfferWithSessions(unittest.TestCase):
    """PartnerOfferWithSessions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerOfferWithSessions(self):
        """Test PartnerOfferWithSessions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerOfferWithSessions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
