"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.partner_asset import PartnerAsset

globals()['PartnerAsset'] = PartnerAsset
from pxcloud_api_client.model.partner_asset_response import PartnerAssetResponse


class TestPartnerAssetResponse(unittest.TestCase):
    """PartnerAssetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerAssetResponse(self):
        """Test PartnerAssetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerAssetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
