"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import pxcloud_api_client
from pxcloud_api_client.api.faults_api import FaultsApi  # noqa: E501


class TestFaultsApi(unittest.TestCase):
    """FaultsApi unit test stubs"""

    def setUp(self):
        self.api = FaultsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fault_affected_assets(self):
        """Test case for fault_affected_assets

        Affected Assets  # noqa: E501
        """
        pass

    def test_fault_history(self):
        """Test case for fault_history

        Assets Fault History  # noqa: E501
        """
        pass

    def test_fault_summary(self):
        """Test case for fault_summary

        Fault summary  # noqa: E501
        """
        pass

    def test_faults(self):
        """Test case for faults

        Faults details  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
