"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.faults_summary import FaultsSummary

globals()['FaultsSummary'] = FaultsSummary
from pxcloud_api_client.model.faults_summary_response import FaultsSummaryResponse


class TestFaultsSummaryResponse(unittest.TestCase):
    """FaultsSummaryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaultsSummaryResponse(self):
        """Test FaultsSummaryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FaultsSummaryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
