"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.racetrack_usecase import RacetrackUsecase

globals()['RacetrackUsecase'] = RacetrackUsecase
from pxcloud_api_client.model.racetrack_buid_solution import RacetrackBuidSolution


class TestRacetrackBuidSolution(unittest.TestCase):
    """RacetrackBuidSolution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRacetrackBuidSolution(self):
        """Test RacetrackBuidSolution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RacetrackBuidSolution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
