"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.suggestion_summary_advisories_severity_exposed import SuggestionSummaryAdvisoriesSeverityExposed


class TestSuggestionSummaryAdvisoriesSeverityExposed(unittest.TestCase):
    """SuggestionSummaryAdvisoriesSeverityExposed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestionSummaryAdvisoriesSeverityExposed(self):
        """Test SuggestionSummaryAdvisoriesSeverityExposed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuggestionSummaryAdvisoriesSeverityExposed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
