"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.suggestion import Suggestion

globals()['Suggestion'] = Suggestion
from pxcloud_api_client.model.suggestions_response import SuggestionsResponse


class TestSuggestionsResponse(unittest.TestCase):
    """SuggestionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestionsResponse(self):
        """Test SuggestionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuggestionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
