"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.suggestion_summary_field_notice_severity_exposed import SuggestionSummaryFieldNoticeSeverityExposed
from pxcloud_api_client.model.suggestion_summary_field_notice_severity_fixed import SuggestionSummaryFieldNoticeSeverityFixed
from pxcloud_api_client.model.suggestion_summary_field_notice_severity_new_exposed import SuggestionSummaryFieldNoticeSeverityNewExposed

globals(
)['SuggestionSummaryFieldNoticeSeverityExposed'] = SuggestionSummaryFieldNoticeSeverityExposed
globals(
)['SuggestionSummaryFieldNoticeSeverityFixed'] = SuggestionSummaryFieldNoticeSeverityFixed
globals(
)['SuggestionSummaryFieldNoticeSeverityNewExposed'] = SuggestionSummaryFieldNoticeSeverityNewExposed
from pxcloud_api_client.model.suggestion_summary_field_notice_severity import SuggestionSummaryFieldNoticeSeverity


class TestSuggestionSummaryFieldNoticeSeverity(unittest.TestCase):
    """SuggestionSummaryFieldNoticeSeverity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestionSummaryFieldNoticeSeverity(self):
        """Test SuggestionSummaryFieldNoticeSeverity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuggestionSummaryFieldNoticeSeverity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
