"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.suggestion_summary_advisories_severity_exposed import SuggestionSummaryAdvisoriesSeverityExposed
from pxcloud_api_client.model.suggestion_summary_advisories_severity_fixed import SuggestionSummaryAdvisoriesSeverityFixed
from pxcloud_api_client.model.suggestion_summary_advisories_severity_new_exposed import SuggestionSummaryAdvisoriesSeverityNewExposed

globals(
)['SuggestionSummaryAdvisoriesSeverityExposed'] = SuggestionSummaryAdvisoriesSeverityExposed
globals(
)['SuggestionSummaryAdvisoriesSeverityFixed'] = SuggestionSummaryAdvisoriesSeverityFixed
globals(
)['SuggestionSummaryAdvisoriesSeverityNewExposed'] = SuggestionSummaryAdvisoriesSeverityNewExposed
from pxcloud_api_client.model.suggestion_summary_advisories_severity import SuggestionSummaryAdvisoriesSeverity


class TestSuggestionSummaryAdvisoriesSeverity(unittest.TestCase):
    """SuggestionSummaryAdvisoriesSeverity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestionSummaryAdvisoriesSeverity(self):
        """Test SuggestionSummaryAdvisoriesSeverity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuggestionSummaryAdvisoriesSeverity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
