"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.software_group_bugs import SoftwareGroupBugs

globals()['SoftwareGroupBugs'] = SoftwareGroupBugs
from pxcloud_api_client.model.software_group_bugs_response import SoftwareGroupBugsResponse


class TestSoftwareGroupBugsResponse(unittest.TestCase):
    """SoftwareGroupBugsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoftwareGroupBugsResponse(self):
        """Test SoftwareGroupBugsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SoftwareGroupBugsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
