"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.contract_v2_details import ContractV2Details

globals()['ContractV2Details'] = ContractV2Details
from pxcloud_api_client.model.contract_details_v2_response import ContractDetailsV2Response


class TestContractDetailsV2Response(unittest.TestCase):
    """ContractDetailsV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractDetailsV2Response(self):
        """Test ContractDetailsV2Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContractDetailsV2Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
