"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.affected_assets import AffectedAssets

globals()['AffectedAssets'] = AffectedAssets
from pxcloud_api_client.model.affected_assets_response import AffectedAssetsResponse


class TestAffectedAssetsResponse(unittest.TestCase):
    """AffectedAssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAffectedAssetsResponse(self):
        """Test AffectedAssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AffectedAssetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
