"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import pxcloud_api_client
from pxcloud_api_client.model.racetrack_buid_pitstop_action import RacetrackBuidPitstopAction

globals()['RacetrackBuidPitstopAction'] = RacetrackBuidPitstopAction
from pxcloud_api_client.model.racetrack_buid_pitstop import RacetrackBuidPitstop


class TestRacetrackBuidPitstop(unittest.TestCase):
    """RacetrackBuidPitstop unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRacetrackBuidPitstop(self):
        """Test RacetrackBuidPitstop"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RacetrackBuidPitstop()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
