"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import pxcloud_api_client
from pxcloud_api_client.api.partner_data_api import PartnerDataApi  # noqa: E501


class TestPartnerDataApi(unittest.TestCase):
    """PartnerDataApi unit test stubs"""

    def setUp(self):
        self.api = PartnerDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_success_tracks(self):
        """Test case for success_tracks

        Success Tracks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
