"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import pxcloud_api_client
from pxcloud_api_client.api.crash_risk_api import CrashRiskApi  # noqa: E501


class TestCrashRiskApi(unittest.TestCase):
    """CrashRiskApi unit test stubs"""

    def setUp(self):
        self.api = CrashRiskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_asset_risk_factors(self):
        """Test case for asset_risk_factors

        Get risk factors of a device  # noqa: E501
        """
        pass

    def test_assets(self):
        """Test case for assets

        Get devices which are at risk of crash owned by a customer, sorted by risk score in descending order by default  # noqa: E501
        """
        pass

    def test_assets_crashed(self):
        """Test case for assets_crashed

        Get the list of crashed devices for last given time period  # noqa: E501
        """
        pass

    def test_crash_history(self):
        """Test case for crash_history

        Get the device crash-detail - Asset 360(time stamp, reset reason)  # noqa: E501
        """
        pass

    def test_similar_assets(self):
        """Test case for similar_assets

        Get similar assets based on the similarity score  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
