from pxcloud_api_client.paths.v1_customers_customer_id_insights_software_software_groups_suggestions_security_advisories.get import ApiForget


class V1CustomersCustomerIdInsightsSoftwareSoftwareGroupsSuggestionsSecurityAdvisories(
    ApiForget,
):
    pass
