"""
    Partner Experience Cloud API Python SDK

    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "pxcloud-api-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "urllib3 >= 1.25.3",
    "python-dateutil",
]

setup(name=NAME,
      version=VERSION,
      description="Partner Experience Cloud API Python SDK",
      author="API Support",
      author_email="partner-support@cisco.com",
      url="",
      keywords=[
          "OpenAPI", "OpenAPI-Generator",
          "Partner Experience Cloud API Python SDK"
      ],
      python_requires=">=3.6",
      install_requires=REQUIRES,
      packages=find_packages(exclude=["test", "tests"]),
      include_package_data=True,
      license="Apache 2.0",
      long_description="""\
    Partner Experience Cloud API Python SDK - LA Release  # noqa: E501
    """)
