"""
    CX Partner Portal APIs

    PX Cloud APIs for the Partners  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_osv_v1_python_sdk.model.suggestion_summary_advisories_severity_inner_new_open import SuggestionSummaryAdvisoriesSeverityInnerNewOpen
from px_osv_v1_python_sdk.model.suggestion_summary_advisories_severity_inner_open import SuggestionSummaryAdvisoriesSeverityInnerOpen
from px_osv_v1_python_sdk.model.suggestion_summary_advisories_severity_inner_resolved import SuggestionSummaryAdvisoriesSeverityInnerResolved
globals()['SuggestionSummaryAdvisoriesSeverityInnerNewOpen'] = SuggestionSummaryAdvisoriesSeverityInnerNewOpen
globals()['SuggestionSummaryAdvisoriesSeverityInnerOpen'] = SuggestionSummaryAdvisoriesSeverityInnerOpen
globals()['SuggestionSummaryAdvisoriesSeverityInnerResolved'] = SuggestionSummaryAdvisoriesSeverityInnerResolved
from px_osv_v1_python_sdk.model.suggestion_summary_advisories_severity_inner import SuggestionSummaryAdvisoriesSeverityInner


class TestSuggestionSummaryAdvisoriesSeverityInner(unittest.TestCase):
    """SuggestionSummaryAdvisoriesSeverityInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuggestionSummaryAdvisoriesSeverityInner(self):
        """Test SuggestionSummaryAdvisoriesSeverityInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuggestionSummaryAdvisoriesSeverityInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
