"""
    CX Partner Portal APIs

    PX Cloud APIs for the Partners  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_osv_v1_python_sdk.model.software_group import SoftwareGroup
globals()['SoftwareGroup'] = SoftwareGroup
from px_osv_v1_python_sdk.model.software_group_response import SoftwareGroupResponse


class TestSoftwareGroupResponse(unittest.TestCase):
    """SoftwareGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSoftwareGroupResponse(self):
        """Test SoftwareGroupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SoftwareGroupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
