"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners. These APIs are subjected to change in the month of August.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_riskcompliance_v1_python_sdk.model.assets_violations import AssetsViolations
globals()['AssetsViolations'] = AssetsViolations
from px_riskcompliance_v1_python_sdk.model.assets_violations_response import AssetsViolationsResponse


class TestAssetsViolationsResponse(unittest.TestCase):
    """AssetsViolationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetsViolationsResponse(self):
        """Test AssetsViolationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetsViolationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
