"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners. These APIs are subjected to change in the month of August.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from px_riskcompliance_v1_python_sdk.api.compliance_api import ComplianceApi  # noqa: E501


class TestComplianceApi(unittest.TestCase):
    """ComplianceApi unit test stubs"""

    def setUp(self):
        self.api = ComplianceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_asset_violation_details_using_get(self):
        """Test case for get_asset_violation_details_using_get

        Get the violation details of impacted assets for the customer, and selected policy Group, Policy and Rule  # noqa: E501
        """
        pass

    def test_get_asset_violations_using_get(self):
        """Test case for get_asset_violations_using_get

        Get the violations of the asset  # noqa: E501
        """
        pass

    def test_get_asset_with_violations_using_get(self):
        """Test case for get_asset_with_violations_using_get

        Get the asset summary  # noqa: E501
        """
        pass

    def test_get_opt_in_using_get(self):
        """Test case for get_opt_in_using_get

        optIn status  # noqa: E501
        """
        pass

    def test_get_policy_rule_details_using_get(self):
        """Test case for get_policy_rule_details_using_get

        Returns information about the policy the rule belongs to  # noqa: E501
        """
        pass

    def test_get_suggestions_using_get(self):
        """Test case for get_suggestions_using_get

        Get the Suggestions filtered upon Severity (if given), for summary tab  # noqa: E501
        """
        pass

    def test_get_violation_summary_using_get(self):
        """Test case for get_violation_summary_using_get

        Get the violation summary of a customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
