# coding: utf-8

"""
    PX Cloud for Success Tracks API

    PX Cloud for Success Tracks API  # noqa: E501

    The version of the OpenAPI document: 0.9.11
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pxcloud_api_client import schemas  # noqa: F401


class CrashRiskDevice(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            assetId = schemas.StrSchema
            assetName = schemas.StrSchema
            assetUniqueId = schemas.StrSchema
            productId = schemas.StrSchema
            productFamily = schemas.StrSchema
            ipAddress = schemas.StrSchema
            softwareRelease = schemas.StrSchema
            softwareType = schemas.StrSchema
            serialNumber = schemas.StrSchema
            risk = schemas.StrSchema
            endDate = schemas.StrSchema
            mgmtSystemType = schemas.StrSchema
            mgmtSystemHostname = schemas.StrSchema
            mgmtSystemAddr = schemas.StrSchema
            __annotations__ = {
                "assetId": assetId,
                "assetName": assetName,
                "assetUniqueId": assetUniqueId,
                "productId": productId,
                "productFamily": productFamily,
                "ipAddress": ipAddress,
                "softwareRelease": softwareRelease,
                "softwareType": softwareType,
                "serialNumber": serialNumber,
                "risk": risk,
                "endDate": endDate,
                "mgmtSystemType": mgmtSystemType,
                "mgmtSystemHostname": mgmtSystemHostname,
                "mgmtSystemAddr": mgmtSystemAddr,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetId"]) -> MetaOapg.properties.assetId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetName"]) -> MetaOapg.properties.assetName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetUniqueId"]) -> MetaOapg.properties.assetUniqueId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["productId"]) -> MetaOapg.properties.productId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["productFamily"]) -> MetaOapg.properties.productFamily: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ipAddress"]) -> MetaOapg.properties.ipAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["softwareRelease"]) -> MetaOapg.properties.softwareRelease: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["softwareType"]) -> MetaOapg.properties.softwareType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["serialNumber"]) -> MetaOapg.properties.serialNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["risk"]) -> MetaOapg.properties.risk: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endDate"]) -> MetaOapg.properties.endDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mgmtSystemType"]) -> MetaOapg.properties.mgmtSystemType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mgmtSystemHostname"]) -> MetaOapg.properties.mgmtSystemHostname: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mgmtSystemAddr"]) -> MetaOapg.properties.mgmtSystemAddr: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["assetId", "assetName", "assetUniqueId", "productId", "productFamily", "ipAddress", "softwareRelease", "softwareType", "serialNumber", "risk", "endDate", "mgmtSystemType", "mgmtSystemHostname", "mgmtSystemAddr", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetId"]) -> typing.Union[MetaOapg.properties.assetId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetName"]) -> typing.Union[MetaOapg.properties.assetName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetUniqueId"]) -> typing.Union[MetaOapg.properties.assetUniqueId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["productId"]) -> typing.Union[MetaOapg.properties.productId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["productFamily"]) -> typing.Union[MetaOapg.properties.productFamily, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ipAddress"]) -> typing.Union[MetaOapg.properties.ipAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["softwareRelease"]) -> typing.Union[MetaOapg.properties.softwareRelease, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["softwareType"]) -> typing.Union[MetaOapg.properties.softwareType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["serialNumber"]) -> typing.Union[MetaOapg.properties.serialNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["risk"]) -> typing.Union[MetaOapg.properties.risk, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endDate"]) -> typing.Union[MetaOapg.properties.endDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mgmtSystemType"]) -> typing.Union[MetaOapg.properties.mgmtSystemType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mgmtSystemHostname"]) -> typing.Union[MetaOapg.properties.mgmtSystemHostname, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mgmtSystemAddr"]) -> typing.Union[MetaOapg.properties.mgmtSystemAddr, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["assetId", "assetName", "assetUniqueId", "productId", "productFamily", "ipAddress", "softwareRelease", "softwareType", "serialNumber", "risk", "endDate", "mgmtSystemType", "mgmtSystemHostname", "mgmtSystemAddr", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        assetId: typing.Union[MetaOapg.properties.assetId, str, schemas.Unset] = schemas.unset,
        assetName: typing.Union[MetaOapg.properties.assetName, str, schemas.Unset] = schemas.unset,
        assetUniqueId: typing.Union[MetaOapg.properties.assetUniqueId, str, schemas.Unset] = schemas.unset,
        productId: typing.Union[MetaOapg.properties.productId, str, schemas.Unset] = schemas.unset,
        productFamily: typing.Union[MetaOapg.properties.productFamily, str, schemas.Unset] = schemas.unset,
        ipAddress: typing.Union[MetaOapg.properties.ipAddress, str, schemas.Unset] = schemas.unset,
        softwareRelease: typing.Union[MetaOapg.properties.softwareRelease, str, schemas.Unset] = schemas.unset,
        softwareType: typing.Union[MetaOapg.properties.softwareType, str, schemas.Unset] = schemas.unset,
        serialNumber: typing.Union[MetaOapg.properties.serialNumber, str, schemas.Unset] = schemas.unset,
        risk: typing.Union[MetaOapg.properties.risk, str, schemas.Unset] = schemas.unset,
        endDate: typing.Union[MetaOapg.properties.endDate, str, schemas.Unset] = schemas.unset,
        mgmtSystemType: typing.Union[MetaOapg.properties.mgmtSystemType, str, schemas.Unset] = schemas.unset,
        mgmtSystemHostname: typing.Union[MetaOapg.properties.mgmtSystemHostname, str, schemas.Unset] = schemas.unset,
        mgmtSystemAddr: typing.Union[MetaOapg.properties.mgmtSystemAddr, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CrashRiskDevice':
        return super().__new__(
            cls,
            *_args,
            assetId=assetId,
            assetName=assetName,
            assetUniqueId=assetUniqueId,
            productId=productId,
            productFamily=productFamily,
            ipAddress=ipAddress,
            softwareRelease=softwareRelease,
            softwareType=softwareType,
            serialNumber=serialNumber,
            risk=risk,
            endDate=endDate,
            mgmtSystemType=mgmtSystemType,
            mgmtSystemHostname=mgmtSystemHostname,
            mgmtSystemAddr=mgmtSystemAddr,
            _configuration=_configuration,
            **kwargs,
        )
