# coding: utf-8

"""
    PX Cloud for Success Tracks API

    PX Cloud for Success Tracks API  # noqa: E501

    The version of the OpenAPI document: 0.9.11
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pxcloud_api_client import schemas  # noqa: F401


class RacetrackUsecase(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "adoptionPercentage",
            "name",
            "description",
            "pitstops",
            "usecaseId",
            "currentPitstop",
        }
        
        class properties:
            name = schemas.StrSchema
            description = schemas.StrSchema
            usecaseId = schemas.StrSchema
            currentPitstop = schemas.StrSchema
            
            
            class pitstops(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['RacetrackBuidPitstop']:
                        return RacetrackBuidPitstop
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['RacetrackBuidPitstop'], typing.List['RacetrackBuidPitstop']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'pitstops':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'RacetrackBuidPitstop':
                    return super().__getitem__(i)
            adoptionPercentage = schemas.IntSchema
            __annotations__ = {
                "name": name,
                "description": description,
                "usecaseId": usecaseId,
                "currentPitstop": currentPitstop,
                "pitstops": pitstops,
                "adoptionPercentage": adoptionPercentage,
            }
    
    adoptionPercentage: MetaOapg.properties.adoptionPercentage
    name: MetaOapg.properties.name
    description: MetaOapg.properties.description
    pitstops: MetaOapg.properties.pitstops
    usecaseId: MetaOapg.properties.usecaseId
    currentPitstop: MetaOapg.properties.currentPitstop
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usecaseId"]) -> MetaOapg.properties.usecaseId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currentPitstop"]) -> MetaOapg.properties.currentPitstop: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pitstops"]) -> MetaOapg.properties.pitstops: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adoptionPercentage"]) -> MetaOapg.properties.adoptionPercentage: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "description", "usecaseId", "currentPitstop", "pitstops", "adoptionPercentage", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usecaseId"]) -> MetaOapg.properties.usecaseId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currentPitstop"]) -> MetaOapg.properties.currentPitstop: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pitstops"]) -> MetaOapg.properties.pitstops: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adoptionPercentage"]) -> MetaOapg.properties.adoptionPercentage: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "description", "usecaseId", "currentPitstop", "pitstops", "adoptionPercentage", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        adoptionPercentage: typing.Union[MetaOapg.properties.adoptionPercentage, decimal.Decimal, int, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        pitstops: typing.Union[MetaOapg.properties.pitstops, list, tuple, ],
        usecaseId: typing.Union[MetaOapg.properties.usecaseId, str, ],
        currentPitstop: typing.Union[MetaOapg.properties.currentPitstop, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RacetrackUsecase':
        return super().__new__(
            cls,
            *_args,
            adoptionPercentage=adoptionPercentage,
            name=name,
            description=description,
            pitstops=pitstops,
            usecaseId=usecaseId,
            currentPitstop=currentPitstop,
            _configuration=_configuration,
            **kwargs,
        )

from pxcloud_api_client.pxcloud_api_client.racetrack_buid_pitstop import RacetrackBuidPitstop
