# coding: utf-8

"""
    PX Cloud for Success Tracks API

    PX Cloud for Success Tracks API  # noqa: E501

    The version of the OpenAPI document: 0.9.11
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pxcloud_api_client import schemas  # noqa: F401


class RacetrackBuidSolution(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "cxLevel",
            "name",
            "description",
            "solutionId",
            "usecases",
        }
        
        class properties:
            name = schemas.StrSchema
            solutionId = schemas.StrSchema
            description = schemas.StrSchema
            cxLevel = schemas.NumberSchema
            
            
            class usecases(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['RacetrackUsecase']:
                        return RacetrackUsecase
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['RacetrackUsecase'], typing.List['RacetrackUsecase']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'usecases':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'RacetrackUsecase':
                    return super().__getitem__(i)
            __annotations__ = {
                "name": name,
                "solutionId": solutionId,
                "description": description,
                "cxLevel": cxLevel,
                "usecases": usecases,
            }
    
    cxLevel: MetaOapg.properties.cxLevel
    name: MetaOapg.properties.name
    description: MetaOapg.properties.description
    solutionId: MetaOapg.properties.solutionId
    usecases: MetaOapg.properties.usecases
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["solutionId"]) -> MetaOapg.properties.solutionId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cxLevel"]) -> MetaOapg.properties.cxLevel: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usecases"]) -> MetaOapg.properties.usecases: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "solutionId", "description", "cxLevel", "usecases", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["solutionId"]) -> MetaOapg.properties.solutionId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cxLevel"]) -> MetaOapg.properties.cxLevel: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usecases"]) -> MetaOapg.properties.usecases: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "solutionId", "description", "cxLevel", "usecases", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        cxLevel: typing.Union[MetaOapg.properties.cxLevel, decimal.Decimal, int, float, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        solutionId: typing.Union[MetaOapg.properties.solutionId, str, ],
        usecases: typing.Union[MetaOapg.properties.usecases, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RacetrackBuidSolution':
        return super().__new__(
            cls,
            *_args,
            cxLevel=cxLevel,
            name=name,
            description=description,
            solutionId=solutionId,
            usecases=usecases,
            _configuration=_configuration,
            **kwargs,
        )

from pxcloud_api_client.pxcloud_api_client.racetrack_usecase import RacetrackUsecase
