# coding: utf-8

"""
    PX Cloud for Success Tracks API

    PX Cloud for Success Tracks API  # noqa: E501

    The version of the OpenAPI document: 0.9.11
    Generated by: https://openapi-generator.tech
"""

from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_asset_violations.get import GetAssetViolations
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_assets_with_violations.get import GetAssetsWithViolations
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_opt_in.get import GetOptIn
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_policy_rule_details.get import GetPolicyRuleDetails
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_suggestions.get import GetSuggestions
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_violations.get import GetViolations
from pxcloud_api_client.paths.v1_customers_customer_id_insights_compliance_violations_assets.get import GetViolationsAssets


class ComplianceApi(
    GetAssetViolations,
    GetAssetsWithViolations,
    GetOptIn,
    GetPolicyRuleDetails,
    GetSuggestions,
    GetViolations,
    GetViolationsAssets,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
