# coding: utf-8

"""
    PX Cloud for Success Tracks API

    PX Cloud for Success Tracks API  # noqa: E501

    The version of the OpenAPI document: 0.9.11
    Generated by: https://openapi-generator.tech
"""

from pxcloud_api_client.paths.v1_customers_customer_id_insights_faults_fault_id_affected_assets.get import GetFaultAffectedAssets
from pxcloud_api_client.paths.v1_customers_customer_id_insights_faults_fault_id_affected_assets_asset_name_fault_history.get import GetFaultHistory
from pxcloud_api_client.paths.v1_customers_customer_id_insights_faults_fault_id_summary.get import GetFaultSummary
from pxcloud_api_client.paths.v1_customers_customer_id_insights_faults.get import GetFaults


class FaultsApi(
    GetFaultAffectedAssets,
    GetFaultHistory,
    GetFaultSummary,
    GetFaults,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
