"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from px_v1_python_sdk.api.partner_offers_sessions_data_api import PartnerOffersSessionsDataApi  # noqa: E501


class TestPartnerOffersSessionsDataApi(unittest.TestCase):
    """PartnerOffersSessionsDataApi unit test stubs"""

    def setUp(self):
        self.api = PartnerOffersSessionsDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_partner_offers_sessions(self):
        """Test case for get_partner_offers_sessions

        Get Info about Partner Offers Sessions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
