"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_v1_python_sdk.model.asset_error import AssetError


class TestAssetError(unittest.TestCase):
    """AssetError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetError(self):
        """Test AssetError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
