"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from px_v1_python_sdk.api.partner_data_api import PartnerDataApi  # noqa: E501


class TestPartnerDataApi(unittest.TestCase):
    """PartnerDataApi unit test stubs"""

    def setUp(self):
        self.api = PartnerDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contracts(self):
        """Test case for get_contracts

        List of contracts  # noqa: E501
        """
        pass

    def test_get_customers(self):
        """Test case for get_customers

        List of customers  # noqa: E501
        """
        pass

    def test_get_success_tracks(self):
        """Test case for get_success_tracks

        Success Tracks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
