"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from px_v1_python_sdk.api.partner_offers_data_api import PartnerOffersDataApi  # noqa: E501


class TestPartnerOffersDataApi(unittest.TestCase):
    """PartnerOffersDataApi unit test stubs"""

    def setUp(self):
        self.api = PartnerOffersDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_partner_offers(self):
        """Test case for get_partner_offers

        Get Partner Offers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
