"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_v1_python_sdk.model.asset_session import AssetSession
from px_v1_python_sdk.model.solution_mapping import SolutionMapping
globals()['AssetSession'] = AssetSession
globals()['SolutionMapping'] = SolutionMapping
from px_v1_python_sdk.model.partner_asset import PartnerAsset


class TestPartnerAsset(unittest.TestCase):
    """PartnerAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerAsset(self):
        """Test PartnerAsset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerAsset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
