"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_v1_python_sdk.model.success_track_checklist_mapping import SuccessTrackChecklistMapping
globals()['SuccessTrackChecklistMapping'] = SuccessTrackChecklistMapping
from px_v1_python_sdk.model.success_track_mapping import SuccessTrackMapping


class TestSuccessTrackMapping(unittest.TestCase):
    """SuccessTrackMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuccessTrackMapping(self):
        """Test SuccessTrackMapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuccessTrackMapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
