"""
    CX Partner Portal APIs

    CX Partner Portal APIs for the Partners - LA Release  # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_v1_python_sdk.model.racetrack_buid_solution import RacetrackBuidSolution
globals()['RacetrackBuidSolution'] = RacetrackBuidSolution
from px_v1_python_sdk.model.racetrack_buid import RacetrackBuid


class TestRacetrackBuid(unittest.TestCase):
    """RacetrackBuid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRacetrackBuid(self):
        """Test RacetrackBuid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RacetrackBuid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
