"""
    CX Partner Portal APIs

    PX Cloud APIs for the Partners  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_faults_v1_python_sdk.model.assets_fault_history import AssetsFaultHistory
globals()['AssetsFaultHistory'] = AssetsFaultHistory
from px_faults_v1_python_sdk.model.assets_fault_history_response import AssetsFaultHistoryResponse


class TestAssetsFaultHistoryResponse(unittest.TestCase):
    """AssetsFaultHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetsFaultHistoryResponse(self):
        """Test AssetsFaultHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetsFaultHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
