"""
    CX Partner Portal APIs

    PX Cloud APIs for the Partners  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: partner-support@cisco.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from px_faults_v1_python_sdk.model.affected_assets import AffectedAssets
globals()['AffectedAssets'] = AffectedAssets
from px_faults_v1_python_sdk.model.affected_assets_response import AffectedAssetsResponse


class TestAffectedAssetsResponse(unittest.TestCase):
    """AffectedAssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAffectedAssetsResponse(self):
        """Test AffectedAssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AffectedAssetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
